[project]
name = "surveypie"
version = "0.0.2"
description = "Polarization indices in Python"
requires-python = ">=3.11"
authors = [{ name = "HackerSpace Trójmiasto", email = "simon@dataverselabs.com" }]
license = "MIT"
readme = "README.md"
packages = [{include = "surveypie", from = "src"}]
repository = "https://github.com/hs3city/surveypie"
keywords = ["statistics", "ordinal scale", "Likert scale", "polarization indices", "inequality indices"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering",
    "Topic :: Sociology"
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.group.dev.dependencies]
black = "^24.4.0"
flake8 = "^7.0.0"
pytest = "^8.1.1"

[tool.poetry.dependencies]
pandas = "^2.3.3"
numpy = "^2.3.5"
scipy = "^1.16.3"
pydantic = "^2.12.5"

[tool.black]
line-length = 120

[tool.pytest.ini_options]
pythonpath = [
  "src"
]


